use std::path::PathBuf;

use serde::{Deserialize, Serialize};

use crate::error::{Error, Result};
use crate::slug::slugify;
use crate::store::{atomic_write, now_rfc3339, Store};

/// A workspace: a folder inside a project's dir, at `<project>/<dir>/<slug>/`.
///
/// Like projects and dirs, the slug is the folder name (derived, not stored).
/// `dir` is likewise derived from the path. The manifest holds `id`,
/// `created_at`, and an optional `description`.
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
pub struct Workspace {
    /// Stable identifier (uuid v7). Survives renames and moves.
    pub id: String,
    /// Folder name; identity within its dir. Derived from the directory.
    #[serde(skip)]
    pub slug: String,
    /// The dir this workspace lives in. Derived from the path.
    #[serde(skip)]
    pub dir: String,
    /// Creation time, RFC3339.
    pub created_at: String,
    /// Optional free-text description.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub description: Option<String>,
}

/// Subfolders created inside every workspace: `src` (worktrees + symlinks),
/// `docs` (artifacts), `agents` (agent sessions, locks, and related state).
pub const SCAFFOLD: [&str; 3] = ["src", "docs", "agents"];

/// Orientation file dropped at each workspace root for AI agents launched there.
/// Written as `AGENTS.md` (the cross-tool standard) with a `CLAUDE.md` symlink,
/// so both Claude Code and AGENTS.md-aware tools pick it up.
const WORKSPACE_GUIDE: &str = "\
# Workspace guide (for AI agents)

This directory is a **mustr workspace** — an isolated unit of work managed by
`mustr`, a CLI command center for coding-agent work. Its data lives under
`~/.mustr/projects/<project>/<dir>/<workspace>/`; that path tells you which
project, dir, and workspace you are in.

A workspace has three subfolders, each with one job:

## `src/` — the code
Git worktrees and/or symlinks to real repositories — where actual source code
lives and where code changes happen.
- It may hold **several** worktrees or symlinks side by side.
- It may be **empty**: not every workspace has code attached yet.
- Each repo under `src/<repo>/` is its own project. **Read and follow that
  repo's own `AGENTS.md`, `CLAUDE.md`, and similar instruction files** before
  changing anything in it.

## `docs/` — the artifacts
Put **everything you produce or gather** here: research, plans, TODOs,
downloaded Jira/Linear tickets, SQL query dumps, analyses, intermediate
results, scratch notes. If it is not source code, it belongs in `docs/`.

## `agents/` — agent state
Records of running and past AI agent sessions: session data, locks, and related
bookkeeping. Treat it as tool-managed; do not put your work artifacts here.

---
Generated by mustr when this workspace was created. Edit freely.
";

/// Outcome of [`remove`].
#[derive(Debug, PartialEq, Eq)]
pub enum Removal {
    /// Permanently deleted.
    Deleted,
    /// Soft-deleted into `trash` under this (possibly auto-suffixed) slug.
    Trashed { slug: String },
}

/// Splits an address `[dir/]slug` into `(dir, slug)`, defaulting the dir to
/// `main`. Both parts are slugified.
pub fn parse_address(input: &str) -> (String, String) {
    match input.split_once('/') {
        Some((dir, slug)) => (slugify(dir), slugify(slug)),
        None => ("main".to_string(), slugify(input)),
    }
}

/// Creates a workspace in `dir` (which must exist) with an optional description.
pub fn add(
    store: &Store,
    project: &str,
    dir: &str,
    slug: &str,
    description: Option<String>,
) -> Result<Workspace> {
    ensure_dir(store, project, dir)?;
    if slug.is_empty() {
        return Err(Error::InvalidName {
            name: slug.to_string(),
        });
    }
    if store.workspace_path(project, dir, slug).exists() {
        return Err(Error::AlreadyExists {
            kind: "workspace",
            slug: slug.to_string(),
        });
    }
    let ws = Workspace {
        id: uuid::Uuid::now_v7().to_string(),
        slug: slug.to_string(),
        dir: dir.to_string(),
        created_at: now_rfc3339(),
        description,
    };
    let path = store.workspace_path(project, dir, slug);
    std::fs::create_dir_all(&path).map_err(|e| Error::io(&path, e))?;
    write_manifest(store, project, &ws)?;
    for sub in SCAFFOLD {
        let sub_path = path.join(sub);
        std::fs::create_dir_all(&sub_path).map_err(|e| Error::io(&sub_path, e))?;
    }
    write_workspace_guide(&path)?;
    Ok(ws)
}

/// Writes the agent orientation file (`AGENTS.md`) and a `CLAUDE.md` symlink to
/// it at the workspace root.
fn write_workspace_guide(workspace_dir: &std::path::Path) -> Result<()> {
    let agents = workspace_dir.join("AGENTS.md");
    std::fs::write(&agents, WORKSPACE_GUIDE).map_err(|e| Error::io(&agents, e))?;

    #[cfg(unix)]
    {
        let claude = workspace_dir.join("CLAUDE.md");
        std::os::unix::fs::symlink("AGENTS.md", &claude).map_err(|e| Error::io(&claude, e))?;
    }
    Ok(())
}

/// Removes a workspace. In `trash`, or with `force`, deletes permanently;
/// otherwise moves it into `trash` (auto-suffixing on a name clash).
pub fn remove(store: &Store, project: &str, dir: &str, slug: &str, force: bool) -> Result<Removal> {
    ensure_dir(store, project, dir)?;
    let path = store.workspace_path(project, dir, slug);
    if !path.exists() {
        return Err(Error::NotFound {
            kind: "workspace",
            slug: slug.to_string(),
        });
    }

    if force || dir == "trash" {
        std::fs::remove_dir_all(&path).map_err(|e| Error::io(&path, e))?;
        return Ok(Removal::Deleted);
    }

    let final_slug = available_slug(store, project, "trash", slug);
    let dest = store.workspace_path(project, "trash", &final_slug);
    std::fs::rename(&path, &dest).map_err(|e| Error::io(&dest, e))?;
    Ok(Removal::Trashed { slug: final_slug })
}

/// Permanently deletes every workspace in `trash`. Returns how many were removed.
pub fn purge(store: &Store, project: &str) -> Result<usize> {
    let trashed = list(store, project, Some("trash"), true)?;
    for ws in &trashed {
        let path = store.workspace_path(project, "trash", &ws.slug);
        std::fs::remove_dir_all(&path).map_err(|e| Error::io(&path, e))?;
    }
    Ok(trashed.len())
}

/// Renames a workspace's slug and/or sets its description. A slug rename moves
/// the folder within the same dir and preserves `id`/`created_at`.
pub fn rename(
    store: &Store,
    project: &str,
    dir: &str,
    slug: &str,
    new_slug: Option<&str>,
    description: Option<&str>,
) -> Result<Workspace> {
    let mut ws = read_manifest(store, project, dir, slug)?;

    if let Some(desc) = description {
        ws.description = if desc.is_empty() {
            None
        } else {
            Some(desc.to_string())
        };
    }

    if let Some(new) = new_slug {
        let new_slug = slugify(new);
        if new_slug.is_empty() {
            return Err(Error::InvalidName {
                name: new.to_string(),
            });
        }
        if new_slug != slug {
            let dest = store.workspace_path(project, dir, &new_slug);
            if dest.exists() {
                return Err(Error::AlreadyExists {
                    kind: "workspace",
                    slug: new_slug,
                });
            }
            std::fs::rename(store.workspace_path(project, dir, slug), &dest)
                .map_err(|e| Error::io(&dest, e))?;
            ws.slug = new_slug;
        }
    }

    write_manifest(store, project, &ws)?;
    Ok(ws)
}

/// Moves a workspace to `target_dir` (which must exist), auto-suffixing on a
/// name clash. Returns the final slug. Moving to the same dir is a no-op.
pub fn move_to_dir(
    store: &Store,
    project: &str,
    dir: &str,
    slug: &str,
    target_dir: &str,
) -> Result<String> {
    ensure_dir(store, project, dir)?;
    if !store.workspace_path(project, dir, slug).exists() {
        return Err(Error::NotFound {
            kind: "workspace",
            slug: slug.to_string(),
        });
    }
    let target = slugify(target_dir);
    ensure_dir(store, project, &target)?;
    if target == dir {
        return Ok(slug.to_string());
    }

    let final_slug = available_slug(store, project, &target, slug);
    let dest = store.workspace_path(project, &target, &final_slug);
    std::fs::rename(store.workspace_path(project, dir, slug), &dest)
        .map_err(|e| Error::io(&dest, e))?;
    Ok(final_slug)
}

/// Lists workspaces. With a `dir`, only that dir (sorted by slug). Without one,
/// every dir in display order — `pinned`, then user dirs newest-first, then
/// `main`, and `trash` last only when `include_trash` — each row carrying its
/// `dir`.
pub fn list(
    store: &Store,
    project: &str,
    dir: Option<&str>,
    include_trash: bool,
) -> Result<Vec<Workspace>> {
    match dir {
        Some(dir) => {
            ensure_dir(store, project, dir)?;
            list_in_dir(store, project, dir)
        }
        None => {
            let mut out = Vec::new();
            for d in listing_dir_order(store, project, include_trash)? {
                out.extend(list_in_dir(store, project, &d)?);
            }
            Ok(out)
        }
    }
}

/// Returns the on-disk path of an existing workspace, for `cd`-style shell use.
pub fn path(store: &Store, project: &str, dir: &str, slug: &str) -> Result<PathBuf> {
    ensure_dir(store, project, dir)?;
    let path = store.workspace_path(project, dir, slug);
    if path.is_dir() {
        Ok(path)
    } else {
        Err(Error::NotFound {
            kind: "workspace",
            slug: slug.to_string(),
        })
    }
}

/// Case-insensitive search across the listed dirs, matching slug or description.
/// Excludes `trash` unless `include_trash`.
pub fn grep(
    store: &Store,
    project: &str,
    query: &str,
    include_trash: bool,
) -> Result<Vec<Workspace>> {
    let query = query.to_lowercase();
    let matches = |ws: &Workspace| {
        ws.slug.to_lowercase().contains(&query)
            || ws
                .description
                .as_deref()
                .is_some_and(|d| d.to_lowercase().contains(&query))
    };
    Ok(list(store, project, None, include_trash)?
        .into_iter()
        .filter(matches)
        .collect())
}

/// Dirs in workspace-listing order: `pinned`, then user dirs newest-first
/// (oldest at the bottom), then `main`, then `trash` when `include_trash`.
fn listing_dir_order(store: &Store, project: &str, include_trash: bool) -> Result<Vec<String>> {
    let dirs = crate::dir::list(store, project)?;
    let mut others: Vec<&crate::dir::Dir> = dirs
        .iter()
        .filter(|d| !crate::dir::RESERVED.contains(&d.slug.as_str()))
        .collect();
    others.sort_by(|a, b| b.created_at.cmp(&a.created_at).then(a.slug.cmp(&b.slug)));

    let mut order = vec!["pinned".to_string()];
    order.extend(others.iter().map(|d| d.slug.clone()));
    order.push("main".to_string());
    if include_trash {
        order.push("trash".to_string());
    }
    Ok(order)
}

/// Validates the project and dir exist, healing the reserved dirs first.
fn ensure_dir(store: &Store, project: &str, dir: &str) -> Result<()> {
    crate::dir::ensure_defaults(store, project)?;
    if store.dir_manifest_path(project, dir).is_file() {
        Ok(())
    } else {
        Err(Error::NotFound {
            kind: "dir",
            slug: dir.to_string(),
        })
    }
}

/// First free slug in `dir`: `slug`, else `slug-2`, `slug-3`, …
fn available_slug(store: &Store, project: &str, dir: &str, slug: &str) -> String {
    if !store.workspace_path(project, dir, slug).exists() {
        return slug.to_string();
    }
    (2..)
        .map(|n| format!("{slug}-{n}"))
        .find(|candidate| !store.workspace_path(project, dir, candidate).exists())
        .expect("an unused suffix always exists")
}

fn list_in_dir(store: &Store, project: &str, dir: &str) -> Result<Vec<Workspace>> {
    let dir_path = store.dir_path(project, dir);
    let mut workspaces = Vec::new();
    for entry in std::fs::read_dir(&dir_path).map_err(|e| Error::io(&dir_path, e))? {
        let entry = entry.map_err(|e| Error::io(&dir_path, e))?;
        let Some(slug) = entry.file_name().to_str().map(str::to_string) else {
            continue;
        };
        if store.workspace_manifest_path(project, dir, &slug).is_file() {
            workspaces.push(read_manifest(store, project, dir, &slug)?);
        }
    }
    workspaces.sort_by(|a, b| a.slug.cmp(&b.slug));
    Ok(workspaces)
}

fn read_manifest(store: &Store, project: &str, dir: &str, slug: &str) -> Result<Workspace> {
    let path = store.workspace_manifest_path(project, dir, slug);
    let raw = match std::fs::read_to_string(&path) {
        Ok(raw) => raw,
        Err(e) if e.kind() == std::io::ErrorKind::NotFound => {
            return Err(Error::NotFound {
                kind: "workspace",
                slug: slug.to_string(),
            })
        }
        Err(e) => return Err(Error::io(&path, e)),
    };
    let mut ws: Workspace =
        toml::from_str(&raw).map_err(|source| Error::TomlRead { path, source })?;
    ws.slug = slug.to_string();
    ws.dir = dir.to_string();
    Ok(ws)
}

fn write_manifest(store: &Store, project: &str, ws: &Workspace) -> Result<()> {
    let path = store.workspace_manifest_path(project, &ws.dir, &ws.slug);
    let raw = toml::to_string_pretty(ws).map_err(|source| Error::TomlWrite {
        path: path.clone(),
        source,
    })?;
    atomic_write(&path, &raw)
}

#[cfg(test)]
mod tests {
    use super::*;
    use time::format_description::well_known::Rfc3339;
    use time::OffsetDateTime;

    fn project_store() -> (tempfile::TempDir, Store) {
        let tmp = tempfile::tempdir().unwrap();
        let store = Store::new(tmp.path());
        store.ensure().unwrap();
        crate::project::add(&store, "proj").unwrap();
        (tmp, store)
    }

    fn add_ws(store: &Store, dir: &str, slug: &str) {
        add(store, "proj", dir, slug, None).unwrap();
    }

    fn slugs(store: &Store, dir: Option<&str>) -> Vec<String> {
        list(store, "proj", dir, true)
            .unwrap()
            .into_iter()
            .map(|w| w.slug)
            .collect()
    }

    #[test]
    fn parse_address_defaults_dir_to_main_and_slugifies() {
        assert_eq!(parse_address("tb-123"), ("main".into(), "tb-123".into()));
        assert_eq!(parse_address("TB-9"), ("main".into(), "tb-9".into()));
        assert_eq!(
            parse_address("pinned/Abc D"),
            ("pinned".into(), "abc-d".into())
        );
        assert_eq!(
            parse_address("trash/tb-123"),
            ("trash".into(), "tb-123".into())
        );
    }

    #[test]
    fn add_creates_scaffold_subdirs() {
        let (_tmp, store) = project_store();
        add_ws(&store, "main", "x");

        let ws = store.workspace_path("proj", "main", "x");
        for sub in ["src", "docs", "agents"] {
            assert!(ws.join(sub).is_dir(), "missing scaffold dir {sub}");
        }
    }

    #[test]
    fn add_writes_agents_guide_and_claude_symlink() {
        let (_tmp, store) = project_store();
        add_ws(&store, "main", "x");
        let ws = store.workspace_path("proj", "main", "x");

        let guide = std::fs::read_to_string(ws.join("AGENTS.md")).unwrap();
        for marker in ["mustr", "src/", "docs/", "agents/"] {
            assert!(guide.contains(marker), "guide missing {marker}");
        }

        // CLAUDE.md is a relative symlink to AGENTS.md so Claude Code picks it up.
        let claude = ws.join("CLAUDE.md");
        assert!(claude.exists());
        assert_eq!(
            std::fs::read_link(&claude).unwrap(),
            std::path::Path::new("AGENTS.md")
        );
    }

    #[test]
    fn add_creates_folder_and_manifest_with_description() {
        let (_tmp, store) = project_store();

        let ws = add(&store, "proj", "main", "tb-123", Some("Fix bug".into())).unwrap();

        assert_eq!(ws.slug, "tb-123");
        assert_eq!(ws.dir, "main");
        assert_eq!(ws.description.as_deref(), Some("Fix bug"));
        assert!(!ws.id.is_empty());
        assert!(OffsetDateTime::parse(&ws.created_at, &Rfc3339).is_ok());
        assert!(store
            .workspace_manifest_path("proj", "main", "tb-123")
            .is_file());
    }

    #[test]
    fn add_without_description() {
        let (_tmp, store) = project_store();
        let ws = add(&store, "proj", "main", "x", None).unwrap();
        assert_eq!(ws.description, None);
    }

    #[test]
    fn add_duplicate_errors() {
        let (_tmp, store) = project_store();
        add_ws(&store, "main", "x");
        assert!(matches!(
            add(&store, "proj", "main", "x", None),
            Err(Error::AlreadyExists {
                kind: "workspace",
                ..
            })
        ));
    }

    #[test]
    fn add_unknown_dir_errors() {
        let (_tmp, store) = project_store();
        assert!(matches!(
            add(&store, "proj", "nope", "x", None),
            Err(Error::NotFound { kind: "dir", .. })
        ));
    }

    #[test]
    fn add_unknown_project_errors() {
        let (_tmp, store) = project_store();
        assert!(matches!(
            add(&store, "ghost", "main", "x", None),
            Err(Error::NotFound {
                kind: "project",
                ..
            })
        ));
    }

    #[test]
    fn add_empty_slug_is_invalid_name() {
        let (_tmp, store) = project_store();
        assert!(matches!(
            add(&store, "proj", "main", "", None),
            Err(Error::InvalidName { .. })
        ));
    }

    #[test]
    fn rm_soft_moves_to_trash() {
        let (_tmp, store) = project_store();
        add_ws(&store, "main", "tb-123");

        let outcome = remove(&store, "proj", "main", "tb-123", false).unwrap();

        assert_eq!(
            outcome,
            Removal::Trashed {
                slug: "tb-123".into()
            }
        );
        assert!(!store.workspace_path("proj", "main", "tb-123").exists());
        assert!(store.workspace_path("proj", "trash", "tb-123").is_dir());
    }

    #[test]
    fn rm_soft_auto_suffixes_on_clash() {
        let (_tmp, store) = project_store();
        add_ws(&store, "main", "tb-123");
        remove(&store, "proj", "main", "tb-123", false).unwrap(); // trash/tb-123
        add_ws(&store, "main", "tb-123");

        let outcome = remove(&store, "proj", "main", "tb-123", false).unwrap();

        assert_eq!(
            outcome,
            Removal::Trashed {
                slug: "tb-123-2".into()
            }
        );
        assert!(store.workspace_path("proj", "trash", "tb-123-2").is_dir());
    }

    #[test]
    fn rm_force_deletes_permanently() {
        let (_tmp, store) = project_store();
        add_ws(&store, "main", "x");

        assert_eq!(
            remove(&store, "proj", "main", "x", true).unwrap(),
            Removal::Deleted
        );
        assert!(!store.workspace_path("proj", "main", "x").exists());
        assert!(slugs(&store, Some("trash")).is_empty());
    }

    #[test]
    fn rm_in_trash_deletes_permanently() {
        let (_tmp, store) = project_store();
        add_ws(&store, "trash", "x");

        assert_eq!(
            remove(&store, "proj", "trash", "x", false).unwrap(),
            Removal::Deleted
        );
        assert!(!store.workspace_path("proj", "trash", "x").exists());
    }

    #[test]
    fn rm_unknown_errors() {
        let (_tmp, store) = project_store();
        assert!(matches!(
            remove(&store, "proj", "main", "ghost", false),
            Err(Error::NotFound {
                kind: "workspace",
                ..
            })
        ));
    }

    #[test]
    fn purge_empties_trash_and_counts() {
        let (_tmp, store) = project_store();
        add_ws(&store, "trash", "a");
        add_ws(&store, "trash", "b");

        assert_eq!(purge(&store, "proj").unwrap(), 2);
        assert!(slugs(&store, Some("trash")).is_empty());
    }

    #[test]
    fn purge_empty_trash_is_zero() {
        let (_tmp, store) = project_store();
        assert_eq!(purge(&store, "proj").unwrap(), 0);
    }

    #[test]
    fn rename_slug_moves_and_preserves_identity() {
        let (_tmp, store) = project_store();
        let original = add(&store, "proj", "main", "tb-123", Some("desc".into())).unwrap();

        let renamed = rename(&store, "proj", "main", "tb-123", Some("tb-3434"), None).unwrap();

        assert_eq!(renamed.slug, "tb-3434");
        assert_eq!(renamed.id, original.id);
        assert_eq!(renamed.created_at, original.created_at);
        assert_eq!(renamed.description.as_deref(), Some("desc"));
        assert!(!store.workspace_path("proj", "main", "tb-123").exists());
        assert!(store
            .workspace_manifest_path("proj", "main", "tb-3434")
            .is_file());
    }

    #[test]
    fn rename_slug_clash_errors() {
        let (_tmp, store) = project_store();
        add_ws(&store, "main", "a");
        add_ws(&store, "main", "b");
        assert!(matches!(
            rename(&store, "proj", "main", "a", Some("b"), None),
            Err(Error::AlreadyExists {
                kind: "workspace",
                ..
            })
        ));
    }

    #[test]
    fn rename_description_only() {
        let (_tmp, store) = project_store();
        add_ws(&store, "main", "x");

        let ws = rename(&store, "proj", "main", "x", None, Some("Social signup")).unwrap();

        assert_eq!(ws.slug, "x");
        assert_eq!(ws.description.as_deref(), Some("Social signup"));
        // Persisted.
        assert_eq!(
            list(&store, "proj", Some("main"), false).unwrap()[0]
                .description
                .as_deref(),
            Some("Social signup")
        );
    }

    #[test]
    fn rename_unknown_errors() {
        let (_tmp, store) = project_store();
        assert!(matches!(
            rename(&store, "proj", "main", "ghost", Some("y"), None),
            Err(Error::NotFound {
                kind: "workspace",
                ..
            })
        ));
    }

    #[test]
    fn mv_moves_between_dirs() {
        let (_tmp, store) = project_store();
        add_ws(&store, "main", "x");

        let final_slug = move_to_dir(&store, "proj", "main", "x", "pinned").unwrap();

        assert_eq!(final_slug, "x");
        assert!(!store.workspace_path("proj", "main", "x").exists());
        assert!(store.workspace_path("proj", "pinned", "x").is_dir());
    }

    #[test]
    fn mv_same_dir_is_noop() {
        let (_tmp, store) = project_store();
        add_ws(&store, "main", "x");
        assert_eq!(
            move_to_dir(&store, "proj", "main", "x", "main").unwrap(),
            "x"
        );
        assert!(store.workspace_path("proj", "main", "x").is_dir());
    }

    #[test]
    fn mv_auto_suffixes_on_clash() {
        let (_tmp, store) = project_store();
        add_ws(&store, "pinned", "x");
        add_ws(&store, "main", "x");

        let final_slug = move_to_dir(&store, "proj", "main", "x", "pinned").unwrap();

        assert_eq!(final_slug, "x-2");
        assert!(store.workspace_path("proj", "pinned", "x-2").is_dir());
    }

    #[test]
    fn mv_unknown_target_errors() {
        let (_tmp, store) = project_store();
        add_ws(&store, "main", "x");
        assert!(matches!(
            move_to_dir(&store, "proj", "main", "x", "nope"),
            Err(Error::NotFound { kind: "dir", .. })
        ));
    }

    #[test]
    fn mv_to_trash_allowed() {
        let (_tmp, store) = project_store();
        add_ws(&store, "main", "x");
        move_to_dir(&store, "proj", "main", "x", "trash").unwrap();
        assert!(store.workspace_path("proj", "trash", "x").is_dir());
    }

    #[test]
    fn list_single_dir_sorted_by_slug() {
        let (_tmp, store) = project_store();
        add_ws(&store, "main", "b");
        add_ws(&store, "main", "a");
        assert_eq!(slugs(&store, Some("main")), vec!["a", "b"]);
    }

    #[test]
    fn list_all_orders_pinned_then_user_dirs_newest_first_then_main() {
        let (_tmp, store) = project_store();
        // User dirs created oldest -> newest.
        crate::dir::add(&store, "proj", "old").unwrap();
        crate::dir::add(&store, "proj", "new").unwrap();
        add_ws(&store, "pinned", "p");
        add_ws(&store, "old", "o");
        add_ws(&store, "new", "n");
        add_ws(&store, "main", "m");

        let pairs: Vec<_> = list(&store, "proj", None, false)
            .unwrap()
            .into_iter()
            .map(|w| (w.dir, w.slug))
            .collect();
        let pairs: Vec<_> = pairs
            .iter()
            .map(|(d, s)| (d.as_str(), s.as_str()))
            .collect();
        assert_eq!(
            pairs,
            vec![("pinned", "p"), ("new", "n"), ("old", "o"), ("main", "m"),]
        );
    }

    #[test]
    fn list_all_excludes_trash_by_default_and_includes_it_when_asked() {
        let (_tmp, store) = project_store();
        add_ws(&store, "main", "m");
        add_ws(&store, "trash", "t");

        let without: Vec<_> = list(&store, "proj", None, false)
            .unwrap()
            .into_iter()
            .map(|w| w.dir)
            .collect();
        assert!(!without.contains(&"trash".to_string()));

        let with: Vec<_> = list(&store, "proj", None, true)
            .unwrap()
            .into_iter()
            .map(|w| w.dir)
            .collect();
        assert!(with.contains(&"trash".to_string()));
    }

    #[test]
    fn list_ignores_stray_entries() {
        let (_tmp, store) = project_store();
        std::fs::create_dir(store.workspace_path("proj", "main", "stray")).unwrap();
        assert!(slugs(&store, Some("main")).is_empty());
    }

    #[test]
    fn grep_matches_slug_and_description_case_insensitive() {
        let (_tmp, store) = project_store();
        add(
            &store,
            "proj",
            "main",
            "login",
            Some("Fix incognito mode".into()),
        )
        .unwrap();
        add(
            &store,
            "proj",
            "pinned",
            "signup",
            Some("Social network".into()),
        )
        .unwrap();

        let by_desc: Vec<_> = grep(&store, "proj", "INCOG", false)
            .unwrap()
            .into_iter()
            .map(|w| w.slug)
            .collect();
        assert_eq!(by_desc, vec!["login"]);

        let by_slug: Vec<_> = grep(&store, "proj", "Sign", false)
            .unwrap()
            .into_iter()
            .map(|w| w.slug)
            .collect();
        assert_eq!(by_slug, vec!["signup"]);
    }

    #[test]
    fn path_returns_dir_for_existing_workspace() {
        let (_tmp, store) = project_store();
        add_ws(&store, "main", "x");
        assert_eq!(
            path(&store, "proj", "main", "x").unwrap(),
            store.workspace_path("proj", "main", "x")
        );
    }

    #[test]
    fn path_unknown_errors() {
        let (_tmp, store) = project_store();
        assert!(matches!(
            path(&store, "proj", "main", "ghost"),
            Err(Error::NotFound {
                kind: "workspace",
                ..
            })
        ));
    }

    #[test]
    fn grep_no_match_is_empty() {
        let (_tmp, store) = project_store();
        add_ws(&store, "main", "x");
        assert!(grep(&store, "proj", "zzz", false).unwrap().is_empty());
    }
}
